function aFE = audioFE (path_senal)
    %Usada para definir los atributos que analizaremos de los audios de
    %entrada.
    [audioInput, fs] = audioread(path_senal);
    %Se definen (inventan) los valores de longitud de la trama y numero de
    %muestras solapadas 
    aFE = audioFeatureExtractor(...
    "SampleRate",fs, ...
    "Window",hamming(round(0.03*fs),"periodic"), ...
    "OverlapLength",round(0.02*fs), ...
    "linearSpectrum", true, ...
    "mfcc",true, ...
    "mfccDelta",true, ...
    "mfccDeltaDelta",true, ...
    "pitch",true, ...
    "spectralCentroid",true);

    features = extract(aFE, audioInput);
    idx = info(aFE);
    disp(idx);
    
    t = linspace(0,size(audioInput,1)/fs,size(features,1));
    plot(t,features(:,idx.pitch))
    title('Pitch')
    xlabel('Time (s)')
    ylabel('Frequency (Hz)')  
end