function aFE = audioFE ()
    %Usada para definir los atributos que analizaremos de los audios
    fs = 44100; 
    %Se definen los valores de longitud de la trama y numero de
    %muestras solapadas 
    aFE = audioFeatureExtractor(...
    "SampleRate",fs, ...
    "Window",hamming(round(0.5*fs),"periodic"), ...
    "OverlapLength",round(0.2*fs), ...
    "mfcc",true, ...
    "mfccDelta",true, ...
    "mfccDeltaDelta",true, ...
    "pitch",true, ...
    "spectralCentroid",true);
end